"""Changes to Unique and Index fields

Revision ID: 0c35915b6cff
Revises: 4518ee4095d0
Create Date: 2025-04-05 15:54:04.772013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c35915b6cff'
down_revision: Union[str, None] = '4518ee4095d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'answer', ['value'])
    op.drop_index('ix_question_id', table_name='question')
    op.create_unique_constraint(None, 'question', ['title'])
    op.drop_index('ix_quiz_id', table_name='quiz')
    op.create_unique_constraint(None, 'quiz', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quiz', type_='unique')
    op.create_index('ix_quiz_id', 'quiz', ['id'], unique=False)
    op.drop_constraint(None, 'question', type_='unique')
    op.create_index('ix_question_id', 'question', ['id'], unique=False)
    op.drop_constraint(None, 'answer', type_='unique')
    # ### end Alembic commands ###
