"""Titles can be the same for diferrent questions

Revision ID: e98656440914
Revises: 107fce55eb0a
Create Date: 2025-04-05 17:30:26.622537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e98656440914'
down_revision: Union[str, None] = '107fce55eb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('answer_value_key', 'answer', type_='unique')
    op.drop_constraint('question_title_key', 'question', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('question_title_key', 'question', ['title'])
    op.create_unique_constraint('answer_value_key', 'answer', ['value'])
    # ### end Alembic commands ###
