"""add active

Revision ID: ebc6fbb64f7d
Revises: 456cbc0ccfc0
Create Date: 2025-04-05 19:13:40.638044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ebc6fbb64f7d'
down_revision: Union[str, None] = '456cbc0ccfc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    op.add_column('question', sa.Column('active', sa.Boolean(), nullable=False, server_default=sa.text('TRUE')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'active')
    op.drop_column('answer', 'active')
    # ### end Alembic commands ###
